export declare const WORLD_CREATE = "Create world access";
export declare const WORLD_ADMIN_ALL = "Able to change permissions for all worlds";
export declare const WORLD_READ_ALL = "Able to read all worlds";
export declare const WORLD_RW_ALL = "Able to write to any world";
export declare const SERVER_ADMIN = "Able to change permissions for this server";
export declare const SERVER_RW = "Able to edit this server";
export declare const SERVER_PERMISSIONS: string[];
export declare const WORLD_READ = "See this world in search results";
export declare const WORLD_ADMIN = "Able to change permissions for this world";
export declare const WORLD_RW = "Able to write to this world";
export declare const WIKI_READ_ALL = "Read all wiki pages";
export declare const WIKI_RW_ALL = "Write to any wiki page";
export declare const WIKI_ADMIN_ALL = "Able to change permissions for any wiki pages";
export declare const FOLDER_READ_ALL = "Read all wiki folders";
export declare const FOLDER_RW_ALL = "Write to any wiki folder";
export declare const FOLDER_ADMIN_ALL = "Able to change permissions for any folder";
export declare const GAME_HOST = "Able to host games";
export declare const GAME_ADMIN_ALL = "Able to change permissions for any game";
export declare const ROLE_ADD = "Able to create roles in this world";
export declare const ROLE_READ_ALL = "Read all roles";
export declare const ROLE_RW_ALL = "Write to any role";
export declare const ROLE_ADMIN_ALL = "Able to change permissions for any role";
export declare const MODEL_ADD = "Able to create models in this world";
export declare const MODEL_READ_ALL = "Read all models";
export declare const MODEL_RW_ALL = "Write to any models";
export declare const MODEL_ADMIN_ALL = "Able to change permissions for any model";
export declare const WORLD_PERMISSIONS: string[];
export declare const ROLE_READ = "Able to see members of this role";
export declare const ROLE_RW = "Able to change members of this role";
export declare const ROLE_ADMIN = "Able to change permissions for this role";
export declare const ROLE_PERMISSIONS: string[];
export declare const WIKI_READ = "Read access to a single wiki page";
export declare const WIKI_RW = "Write access to a single wiki page";
export declare const WIKI_ADMIN = "Able to change permissions for a single wiki page";
export declare const WIKI_PERMISSIONS: string[];
export declare const FOLDER_READ = "Read access to a single wiki folder";
export declare const FOLDER_RW = "Write access to a single wiki folder";
export declare const FOLDER_ADMIN = "Able to change permissions for a single wiki folder";
export declare const FOLDER_READ_ALL_CHILDREN = "Able to read any direct child folder of a wiki folder";
export declare const FOLDER_RW_ALL_CHILDREN = "Able to write to any direct child folder of a wiki folder";
export declare const FOLDER_READ_ALL_PAGES = "Able to read any wiki page in a wiki folder";
export declare const FOLDER_RW_ALL_PAGES = "Able to write to any wiki page in a wiki folder";
export declare const WIKI_FOLDER_PERMISSIONS: string[];
export declare const MODEL_READ = "Read access to a single model";
export declare const MODEL_RW = "Edit access to a single model";
export declare const MODEL_ADMIN = "Able to change permissions for a single model";
export declare const MODEL_PERMISSIONS: string[];
export declare const GAME_READ = "Read access to a single game";
export declare const GAME_PAINT = "Access to paint in a game";
export declare const GAME_MODEL = "Access to add, remove, or change models in a game";
export declare const GAME_FOG_WRITE = "Access to edit fog of a single game";
export declare const GAME_ADMIN = "Able to change permissions for a single game";
export declare const GAME_RW = "Able to change the location for a game";
export declare const GAME_PERMISSIONS: string[];
export declare const ALL_PERMISSIONS: string[];
export declare const PUBLIC_WORLD_PERMISSIONS: string[];
export declare const getPermissionsBySubjectType: (subjectType: string) => string[];
export declare const ANON_USERNAME = "Anonymous";
export declare const SERVER_ADMIN_ROLE = "Server Admin";
