export declare const ARTICLE = "Article";
export declare const PERSON = "Person";
export declare const PLACE = "Place";
export declare const ITEM = "Item";
export declare const FILE = "File";
export declare const MONSTER = "Monster";
export declare const IMAGE = "Image";
export declare const CHUNK = "Chunk";
export declare const GAME = "Game";
export declare const PERMISSION_ASSIGNMENT = "PermissionAssignment";
export declare const PIN = "Pin";
export declare const ROLE = "Role";
export declare const SERVER_CONFIG = "ServerConfig";
export declare const USER = "User";
export declare const WIKI_FOLDER = "WikiFolder";
export declare const WIKI_PAGE = "WikiPage";
export declare const WORLD = "World";
export declare const MODEL = "Model";
export declare const ALL_WIKI_TYPES: string[];
export declare const MODELED_WIKI_TYPES: string[];
export declare const PERMISSION_CONTROLLED_TYPES: string[];
