name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.14.0
    - uses: actions/checkout@v3
    - name: CI
      run: make ci
    - uses: actions/upload-artifact@v3
      with:
        name: e2e-videos
        path: /home/runner/work/rpgtools/rpgtools/packages/frontend/cypress/videos
    - name: Publish Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: make publish
